### ISSUE TITLE
Shadowlands API Updates?

### ISSUE THREAD

**Issue by Brusalk** [wartoshika/wow-declarations#12]
Any plans for updates for shadowlands?

**Comment by wartoshika** [comment]
My plans are currently adding more definitions when shadowlands is released. If you want to have support for specific functions or objects before general release of shadowlands you may submit a pull request.

**Comment by Brusalk** [comment]
Sounds good. I wanted to make sure whether you were or weren't in the process of anything at this moment so we could avoid duplicating work.

**Comment by wartoshika** [comment]
It has been a long time since Shadowlands habe been released. I have published the currently partial implementation of its API. Please consider open a PR if you find require missing declarations.

Thanks
