### ISSUE TITLE
Trouble with importing declarations.

### ISSUE THREAD

**Issue by Brusalk** [wartoshika/wow-declarations#13]
There's quite a few functions/constants/etc that are _not_ included in the WoWAPI namespace, and as a result they don't appear to be usable.

I have wow declarations defined in tsconfig:
```
    "typeRoots": [
      "node_modules/@wartoshika/wow-declarations/declarations",
      "node_modules/lua-types/5.1"
    ],
```

For example, `CreateFrame` (from `ui.d.ts` is not resolvable. 

Full project is here: https://github.com/Brusalk/tsCoolDown

**Comment by wartoshika** [comment]
I will try to spend some time this weekend to confirm this and find a way to fix it. Ill let you know when i have more information about a possible fix.

Thanks

**Comment by Brusalk** [comment]
I ended up figuring out my issue. I _also_ needed to add `types` to my compiler options:

```
    "typeRoots": [
      "node_modules/@wartoshika/wow-declarations",
      "node_modules/lua-types/5.1"
    ],
    "types": [
      "@wartoshika/wow-declarations",
      "lua-types/5.1",
    ],
```

I'll make a PR shortly for the readme to help other noobs like me :) 

Thanks for the awesome package!

**Comment by wartoshika** [comment]
Thanks you sharing your solution. Please reopen this issue if you still have problems. I PR whould be nice. Thanks you using :)
