### ISSUE TITLE
API Methods that return a tuple is not working

### ISSUE THREAD

**Issue by Singatias** [wartoshika/wow-declarations#14]
Hi,

I've wrote a a sample of the issue I found with methods that suppose to return a tuple in lua.

typescript source
```
export class App {
  constructor() {
    print("Hello World of Warcraft", "This is my Typescript addon!");
    
    const frame = CreateFrame("Frame", null, UIParent);
    frame.SetScript("OnUpdate", (frame, elapsed) => {

      let test = GetActionCooldown(1);
      print(`${test[0]}, ${test[1]}, ${test[2]}`);
    });
    frame.Show();
  }
}
```

lua result
```
function App.__init(self)
  print("Hello World of Warcraft", "This is my Typescript addon!")
  local frame = CreateFrame("Frame", nil, UIParent)
  frame:SetScript("OnUpdate", function (frame, elapsed)
    local test = GetActionCooldown(1)
    print("" .. tostring(test[(tonumber(0) + 1)]) .. ", " .. tostring(test[(tonumber(1) + 1)]) .. ", " .. tostring(test[(tonumber(2) + 1)]) .. "")
  end)
  frame:Show()
end
```

error
<img width="307" alt="88a8260bb8891fc772f5f8ed9657eccb" src="https://user-images.githubusercontent.com/71574070/95030700-6fb9e880-067f-11eb-9c97-450df68fad23.png">

Expected behaviour:
Lua Transpiler convert typescript tuple properly (I actually have no clue since you will need to give X different variable name from the typescript tuple (array)

Thanks

UPDATE:
I found the solution, I didn't know you could do this in typescript:
```
 let [start, duration, enable] = GetActionCooldown(1);
 print(`${start}, ${duration}, ${enable}`);
```

**Comment by wartoshika** [comment]
Thanks for providing a solution for your problem. You may find additional lua or wow specific documentation within the transpiler repository documentation at [readme lua](https://github.com/wartoshika/qhun-transpiler/blob/master/doc/lua.md).

Since you found a solution i consider this problem to be solved. Reopen the ticket if you have still problems.
Thanks for using the software!
