### ISSUE TITLE
Slash command SlashCmdList global?

### ISSUE THREAD

**Issue by rob893** [wartoshika/wow-declarations#15]
I can't seem to find any typing for the SlashCmdList object used to register slash commands. Did I miss this?

**Comment by wartoshika** [comment]
They are missing, this is correct. If you can spare some time you may open a PR and implement these missing declarations.
I don't have time (at least atm) to implement these myself, sorry.

**Comment by rob893** [comment]
Sure. I can do this.

**Comment by rob893** [comment]
PR up https://github.com/wartoshika/wow-declarations/pull/16

**Comment by wartoshika** [comment]
PR #16 has been merged and released into the Shadowlands update release.
Thanks for contributing!
