### ISSUE TITLE
Please publish latest fix on npm as well

### ISSUE THREAD

**Issue by jejanim** [wartoshika/wow-declarations#19]
The fix for `error TS2304: Cannot find name 'AtlasID'.` is not pushed to npm despite the version being the same as the release in github.
(See https://github.com/wartoshika/wow-declarations/commit/0e4b87da9df6284263a90f87a3b13eac3c450304)

Please provide this fix to npm users as well, thank you.

**Comment by wartoshika** [comment]
Thanks for pointing this out. I will update the package and let you know.

**Comment by wartoshika** [comment]
I have created a new version and uploaded the current version into npm.

https://www.npmjs.com/package/@wartoshika/wow-declarations/v/9.0.5-release.2

Thank you
