### ISSUE TITLE
Auto formatting settings?

### ISSUE THREAD

**Issue by tstirrat** [wartoshika/wow-declarations#4]
Are you using Prettier etc?

Can you commit your `settings.json` or `.prettierrc` so that auto formatting settings are declared in the repo?

I am trying to create minimal diffs but every time I save it's reformatting..

Seems like you have this:

settings.json:

```json
{
  "editor.tabSize": 4,
  "files.trimFinalNewlines": false,
  "files.trimTrailingWhitespace": false,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}

```

**Comment by wartoshika** [comment]
I added `tslint` to this project. This should help that formatting issues are present. Does this fit your needs?

**Comment by tstirrat** [comment]
Will check!

**Comment by wartoshika** [comment]
Please reopen this issue if you think that `tslint` does not fit your needs.
