### ISSUE TITLE
Nest interfaces under a WoWAPI namespace

### ISSUE THREAD

**Issue by martinjlowm** [wartoshika/wow-declarations#9]
I noticed all interfaces are prefixed with `Wow<decl>`, would you be interested in migrating to a `WoWAPI` namespace instead? It'll end up cleaner in my opinion. For reference, check out how I do it: https://github.com/martinjlowm/types-wow-api/blob/master/src/widgets/frame.d.ts 

Your declaration collection seems more complete than mine, so I'm willing to help migrating existing types to this namespaced approach.

As a bonus it enables the use of `WoWAPI.Object`, which, within the namespace, can be referenced directly as `Object`, which will not interfere with JavaScript's declaration.

**Comment by wartoshika** [comment]
I will check this out and let you know.

**Comment by martinjlowm** [comment]
I went ahead and migrated everything to this format: https://github.com/martinjlowm/wow-declarations/tree/refactor/nest-types-interfaces-under-wowapi

Let me know if I should create a PR.

At this point, the namespace can even be exported with:

```
export = WoWAPI;
export as namespace WoWAPI;
```

Enabling the use of the API as such:
```
import { Frame } from '@wartoshika/wow-declarations';
let f: Frame;
```

**Comment by wartoshika** [comment]
I originally wrote this declaration files for my own transpiler. I will clone your fork and run some tests with it.

If i understand your changes correctly then everything is backwards compatible. In this case a pull request will be nice!

I hope that i can finish my tests within this weekend.

**Comment by wartoshika** [comment]
I think that your changes will make things better. If you could create your PR, ill check things out and will release a new version with your changes.

Thanks!

**Comment by martinjlowm** [comment]
Sure! I'll get on to it tomorrow.

**Comment by wartoshika** [comment]
Closing issue since the PR has been merged. Thanks!
